"" Shavakan's .vimrc file (r01, 2016-09-27)
"" Written by ChangWon Lee <chiyah92@gmail.com>
"" Inspired by lifthrasiir (Kang Seonghoon <lifthrasiir@gmail.com>)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

scripte utf-8

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif


"" Vundle configuration -------------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin()

" Let Vundle manage Vundle, required
" Plug 'VundleVim/Vundle.vim'
" Vim-script library
Plug 'ascenator/L9'
" A tree explorer plugin for vim
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'preservim/tagbar'
Plug 'vim-airline/vim-airline'
" Vim plugin to list, select and switch between buffers
" Plug 'Buffergator'
" A better JSON for Vim: distinct highlighting of keywords vs values,
" JSON-specific (non-JS) warnings, quote concealing
Plug 'elzr/vim-json'
" HTML5 omnicomplete and syntax
Plug 'othree/html5.vim'
" Add CSS3 syntax support to vim's built-in 'syntax/css.vim'
Plug 'hail2u/vim-css3-syntax'
" Vim python-mode, PyLint, Rope, Pydoc, breakpoints from box
Plug 'klen/python-mode'
" Syntax checking hacks for vim
Plug 'scrooloose/syntastic'
" Vim Git runtime files
Plug 'tpope/vim-git'
" A Git wrapper so awesome, it should be illegal
Plug 'tpope/vim-fugitive'
" A git commit browser
Plug 'junegunn/gv.vim'
" One colorscheme pack to rule them all!
Plug 'flazz/vim-colorschemes'
" Make Vim persist editing state without fuss
Plug 'kopischke/vim-stay'
" Vastly improved Javascript indentation and syntax support in Vim
Plug 'pangloss/vim-javascript'
" commentary.vim: comment stuff out
Plug 'tpope/vim-commentary'
" `self-contained and faily explanatory` agglomeration of HashiVim plugins
Plug 'hashivim/vim-hashicorp-tools'
" A (Neo)Vim Autocompletion and linter for Terraform, a HashiCorp tool
Plug 'juliosueiras/vim-terraform-completion'
" React JSX syntax highlighting and indenting for vom.
Plug 'mxw/vim-jsx'
" Syntax Highlight for Vue.js components
Plug 'posva/vim-vue'
" Jsonnet filetype plugin for Vim.
" Plug 'google/vim-jsonnet'

" All of your Plugins must be added before the following line
call plug#end()              " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"" ----------------------------------------------------------------

"" Syntax ---------------------------------------------------------
syn enable
syn sync fromstart
filetype plugin indent on

" AUTOCMD {{ ------------------------------------------------------
autocmd BufRead,BufNewFile *.capnp set filetype=capnp
autocmd BufRead,BufNewFile *.tf set filetype=terraform
autocmd FileType gitcommit DiffGitCached | wincmd L | wincmd p

if has("autocmd")
        aug vimrc
        au!

        " filetype-specific configurations
        au FileType python setl ts=8 sw=4 sts=4 et
        au FileType yaml setl ts=8 sw=2 sts=2 et
        au FileType sh setl ts=2 sw=4 sts=4 et
        au FileType c setl ts=8 sw=4 sts=4 et
        au FileType html setl ts=8 sw=2 sts=2 et
        au FileType css setl ts=8 sw=4 sts=4 et
        au FileType javascript setl ts=2 sw=2 sts=2 et
        au FileType terraform setl ts=8 sw=2 sts=2 et
        au FileType cpp setl ts=8 sw=4 sts=4 et
        au FileType java setl ts=4 sw=4 sts=0 noet
        au FileType php setl ts=8 sw=4 sts=4 et
        au FileType asp setl ts=8 sw=4 sts=4 et
        au FileType jsp setl ts=8 sw=4 sts=4 et
        au FileType ruby setl ts=8 sw=4 sts=4 et
        au FileType capnp setl ts=2 sw=2 sts=2 et
        au FileType jsx sync fromstart ts=2 sw=2 sts=2 et
        au FileType vue syntax sync fromstart ts=2 sw=2 sts=2 et
        au FileType text setl tw=80

        " resotre cursor position when the ifle has beenr ead
        au BufReadPost *
                \ if line("'\"") > 0 && line("'\"") <= line("$") |
                \   exe "norm g`\"" |
                \ endif

        " fix window position for mac os x
        if has("gui_running") && has("macunix")
                au GUIEnter *
                        \ if getwinposx() < 50 |
                        \   exe ':winp 50 ' . (getwinposy() + 22) |
                        \ endif
        endif

        aug END
endif
" -----------------------------------------------------------------

" Set colorscheme
colorscheme Tomorrow-Night
hi Normal ctermbg=none
hi NonText ctermbg=none
" -----------------------------------------------------------------

"" Editor ---------------------------------------------------------
set mouse=a                             " -- mouse cursor on
set noet bs=2 ts=4 sw=8 sts=0           " -- tabstop
set noai nosi hls is ic cf ws scs magic " -- search
set nu ru sc wrap ls=2 lz               " -- appearance
set expandtab                           " -- tab as spaces
set clipboard=unnamed                   " -- clipboard usage on macOS

" encoding and file format
set fenc=utf-8 ff=unix ffs=unix,dos,mac
set fencs=utf-8,cp949,cp932,euc-jp,shift-jis,big5,latin2,ucs2-le
"" ----------------------------------------------------------------

"" Configuration Variables ----------------------------------------
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_flow = 1

" vim-terraform
let g:terraform_align=1
let g:terraform_remap_spacebar=1
autocmd FileType terraform setlocal commentstring=#%s
"" ----------------------------------------------------------------

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" CHANGELOGS :
"" 2016-09-27  Initial revision
""
"" TODOS :
""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
